FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Install runtime dependencies
RUN pip install -U pip && \
    pip install -U \
    uvicorn==0.34.3 \
    requests==2.32.3 \
    surrealdb==1.0.4 \
    boto3==1.38.44 \
    python-multipart

# Copy only what we need
COPY backend_module ./backend_module
COPY query ./query
COPY cleaner_manager.py ./

CMD ["python", "cleaner_manager.py"]
