FROM ubuntu:jammy-20250530
RUN apt update && apt install -y \
    python3 \
    python3-dev \
    python3-pip
RUN python3 -m pip install \
    psutil \
    surrealdb==1.0.4 \
    pynvml

WORKDIR /app

COPY backend_module ./backend_module
COPY hardware_metrics_manager.py ./
CMD ["python3", "hardware_metrics_manager.py"]
